### ISSUE TITLE
As a user, I should be able to check which prereqs I have installed

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1047]
## Description

As a user, I should be able to see which prereqs I have installed on my machine, in addition to the prereqs that I need to install.

I should be able to see the version of the prereq that is required, as well as the version that is installed on my machine.

**Comment by simran-sohanpal** [comment]
https://ibm.box.com/s/4gbdnyriwh3wi7ck3dsuvcx5pots2lmd

Box file with pre-reqs WIP - needs a look from @EdMoffatt then hand off to @Jakeeyturner

**Comment by EdMoffatt** [comment]
Catching up some Slack discussions on GitHub...

**Jake:**
Hey Ed - I've just picked up the pre-reqs work again and a few things have come up.
In a show n' troll it was mentioned that it might be good to display some info on each dependency (what it does, what it's needed for - just some ideas). I'm also wondering if it's a good idea to mention the system requirements for starting a Local Fabric, e.g. 4gb of RAM.
Caroline also mentioned that we might want to display something on the pre-req page which lets a user skip the pre-req page (and maybe display a message that they can get here again if they run the command & if they have installed everything but the prereq page says otherwise, to raise an issue on GitHub).
Just wondering if I'd be able to get some design input regarding these things?

**Ed:**
Made this mockup...
![image](https://user-images.githubusercontent.com/7454304/62294667-632a7680-b463-11e9-896c-ad542f6a4419.png)


Things of note therein...
1. Hovering over tiles could reveal info popups about why that prerequisite is needed
2. Switched the wording of the "I understand" checkboxes to "I confirm" (and tweaked the wording on the tiles to match", to make this feel like a more "active" approval.
3. Added a "System Requirements" confirmation. Note I'm not sure what would actually go there yet, so just used Jake's one example of 4GB RAM
4. Added the "Important" box which offers a route to skip the prerequisite check if really needed.

Note that page is now mostly built out of IBP UI components, so it might be worth having a chat to Shaun Lynch about the stylings to see if we can drop in any existing stuff from IBP :)
