### ISSUE TITLE
Supplying the filename for a Connection Profile to create a Gateway is not successful

### ISSUE THREAD

**Issue by rthatcher** [IBM-Blockchain/blockchain-vscode-extension#1049]
When adding a new gateway I am invited to 'Enter a file path to a connection profile file' but when I paste the name I can't press Enter.  I am forced to go through the Browse dialogs.

With v1.0.1 and v1.0.2 (Ubuntu 18.04 and 16.04)

**Comment by Jakeeyturner** [comment]
For this issue, I see two different potential solutions.
Currently this question is presented when we call `showQuickPick`, and we only offer a dropdown selection of 'Browse'. The original reason for showing this 'Browse' option is that otherwise a file browser is opened and a user has no context of what's happening. By calling `showQuickPick`, a user is shown some text and is able to select one of the presented options.

In order to type in a path and press Enter for this question, we would have to use `showInputBox` instead. By doing this, we would be unable to let a user select a file from the file browser.

One solution would be to simply change the text to indicate that a file path can't be entered, but must be selected using the file browser.

Another solution could be to offer another dropdown option (like 'Browse'), such as 'Enter path', which calls `showInputBox` and lets the user type/paste in their connection profile path. Additionally, we could even have an option which reads directly from the users clipboard.

What do you think @EdMoffatt?

**Comment by cazfletch** [comment]
The remote development extension has a drop down list and lets you type, we should do that

**Comment by EdMoffatt** [comment]
Adding this one to the current sprint design work

**Comment by EdMoffatt** [comment]
I personally can't discover the command @cazfletch is talking about in the Remote Development extension. If you know the one, could you paste in some screenshots please?
The closest thing I can find are commands where there's a dropdown list and typing into the box effectively filters down that dropdown list (e.g. the `remote-ssh: open configuration file...` command).

Feel like most of our commands where you're asked to provide a file only offer you the browse option, like for example "import (smart contract) package":

![image](https://user-images.githubusercontent.com/7454304/71718719-0701bf00-2e14-11ea-942a-70fbd4c0bae5.png)

You _can_ type into that box, in which case it behaves similarly to the one I mentioned from Remote Development, i.e.:

![image](https://user-images.githubusercontent.com/7454304/71718820-547e2c00-2e14-11ea-8a81-7399afb1662b.png)

![image](https://user-images.githubusercontent.com/7454304/71718879-87282480-2e14-11ea-85a1-60ed393b2c1d.png)

We haven't had anyone typing into those boxes and raising issues tho, so I think the difference here is that we updated the behaviour to browse but not the prompt.

I'd be fine with the fix of just switching the prompt here to say: "Browse for a connection profile file", as that seems consistent with our other similar commands.

**Comment by cazfletch** [comment]
i think they have changed the remote development extension to not have what i was talking about.

Ok lets just update the wording

**Comment by jt-nti** [comment]
This is a very old issue, closing
