### ISSUE TITLE
as a user i can create a gateway from a new environment

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1109]

**Comment by EdMoffatt** [comment]
I think this issue is saying:

If the user has created a "Fabric Environment" connection to a runtime (for performing install/instantiate/upgrade operations), we already have all the info we need to create a "Fabric Gateway" connection (for submitting/evaluating transactions). So, let's allow them to take an action on the Environment to create a Gateway.

(Correct me if I'm wrong!)

**Comment by cazfletch** [comment]
closing as not needed you would create the environment first then create the gateway
