### ISSUE TITLE
improve submit transaction

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1155]
Submitting a transaction is ok if you just have strings as parameters but it is not ideal if you have objects especially if they are large objects. We should provide a way of submitting a transaction more easily with objects. It would also be good to be able to repeatedly submit transactions without having to go through the process of typing in the parameters again.

**Comment by EdMoffatt** [comment]
Another one for you Charlotte. I think Andy Hurt or Liam Grace would be good folks to explain to you what's needed here :) Similar plan to the events one, do some research, come up with some suggestions, and then let's review both of them in one meeting with the VS Code squad :+1:

**Comment by awjh-ibm** [comment]
Would be great if my previous inputs were selectable below (in the style of the selecting a function) and also if the form could tell me the arg names not just to enter arg0 etc

**Comment by Charlotte8699** [comment]
Transaction web view update

This is the latest click through of the transactions:
https://xd.adobe.com/view/7b0c6b7e-21b5-46fa-64d7-14b5d4c17091-0d3d/

I've since had further feedback from Liam which I'll be acting on today/tomorrow. I have also been working with @erin-hughes to find out what i need to be doing to make creating this web view easier for her.

**Comment by EdMoffatt** [comment]
Great progress on this @Charlotte8699 . I wonder how it would look without the twisties in the "Recent" view? I think a permanently displayed table could work here, with new transactions appearing at the top - collapsing by date doesn't seem to add much to me!

**Comment by awjh-ibm** [comment]
Has any thought been put into how i might run this using keyboard shortcuts? Ideally I would like to look at my code whilst I run the command. I usually do most of my repeatable transactions when i am in debug mode and like to stay on the same code page so I can view the values in variables as it goes through breakpoints. 

The current method of runnign transactions is nice as I can do it entirely from my keyboard. CMD+L I have configured to bring up the Evaluate vs Submit options and can then use arrow keys and enter to select the transaction and run it.

**Comment by cazfletch** [comment]
I don't think you would want the alternatives for arguments as you don't have key value pairs for arguments, this would work for transient data though. It would also need an `ecert` property (this can either be true or false) as well as the name and value properties you have

**Comment by Jakeeyturner** [comment]
With the work happening in #1510, we'll also need to be able to handle peer-targeting in the new transaction page.

**Comment by Charlotte8699** [comment]
Update on the transactions - I've started looking at spacing more closely and added in the section on targeting a peer. I've split the transient data into key/value instead of arguments as well.

![Screenshot 2019-10-14 at 16 45 18](https://user-images.githubusercontent.com/52786879/66764597-0bb47800-eea2-11e9-87a9-34131fce97e7.png)

**Comment by Charlotte8699** [comment]
Changed the format for the custom peers and adjusted the wording on the filters. Hoping to get a flow for this done today.
Please let me know what you think!
@Jakeeyturner @cazfletch @EdMoffatt @erin-hughes 

![Screenshot 2019-10-17 at 10 48 52](https://user-images.githubusercontent.com/52786879/66998249-d7240480-f0cb-11e9-90e8-945f02190767.png)

**Comment by Charlotte8699** [comment]
Created a flow for when a user would create a transaction, save a transaction and then use the filters. If there are other flows people would like to see, let me know.

@sstone1 Ed recommended I show you this.
https://xd.adobe.com/view/e9fb7327-3b80-4c8d-7b8e-e99976027cdb-9fca/

**Comment by cazfletch** [comment]
@Charlotte8699 i noticed that export was only on a saved one, just wondered if users might also want to export on none saved ones? I can see an argument for both sides though. 

Can we get a flow for import, i remember us talking about that i wasn't sure how it would work

**Comment by Charlotte8699** [comment]
I've created a mock up for importing and exporting transactions here
https://xd.adobe.com/view/cd15fd26-5440-47b6-5924-64e0b4a17558-bb24/

I was thinking of not making it possible to export non saved transactions - as transactions will have to have a copy saved to be exported to another user anyway. 
The format of this export/import is still to be determined. I'll speak to @sstone1 today after retro today.

**Comment by Charlotte8699** [comment]
I had a feedback session with @EdMoffatt and Shaun yesterday and they gave some helpful feedback. Lots of words incoming!

**Summary**
The home page and filters have had some slight phrasing changes
- 'Create a new transaction' has become 'Submit/evaluate a transaction'
- I have deleted the filter for controlling how many transactions are shown in the history
- The output will automatically be on
- Some information has been put in about what gateway the user is in (Local Fabric)

Home page
![Screenshot 2019-10-22 at 11 15 48](https://user-images.githubusercontent.com/52786879/67276790-4e3b0d80-f4bd-11e9-82bc-6e728a000d7f.png)


**The main thing that came up to clarify would be the behaviour of saving transactions**
**Recap on saving transactions**
- Transaction is saved

**Scenario 1 - Submitting changes to saved transaction without saving the changes**
- Change arguments
- Submit transaction with no change to time stamp for saved transaction as the changes haven't been saved
- New transaction added to recent 

**Scenario 2 - User changes info and saves without submitting**
- Name and args change
- Transaction saves and updates the transaction time stamp
- No transaction added to recent as nothing has been submitted/evaluated

**Scenario 3 - User makes changes and doesn't save/submit**
- User makes changes to transaction
- Visits homepage without saving or submitting
- Returns to transaction to see that none of the changes have been saved



@cazfletch Is the ability to add more than one set of both arguments and transient data useful? 

If so, would the current layout be better - so adding sets of transient data and arguments individually.

Or, would dividing the transient data and arguments up into sets - so they come in pairs like this.
![Screenshot 2019-10-22 at 11 28 11](https://user-images.githubusercontent.com/52786879/67277586-0917db00-f4bf-11e9-8c19-3eb98d33d6f3.png)

**Comment by cazfletch** [comment]
I don't think having sets of arguments is useful, i think if you would save multiple transactions in that case with the different arguments

**Comment by Charlotte8699** [comment]
No problem, i've deleted that feature. I haven't redone the flows above as the saved interactions won't be affected by this.

![Screenshot 2019-10-22 at 16 26 34](https://user-images.githubusercontent.com/52786879/67302388-b9e6a000-f4e8-11e9-9253-5ea85d5439ac.png)

**Comment by Charlotte8699** [comment]
Lots of great feedback from Joe Payne and Tom Appleyard!

- They would like to be able to enter multiple sets of arguments for 1 transaction rather than submit multiple transactions of the same type.
- Have a warning with the arguments box that states whatever is entered will be 'stringified'. 
- Have argument box as 1 line with the ability to expand it should the argument take up more than 1 line (they mentioned the phrase 'mono spacing', I assume this means each line has a set spacing where the box increases incrementally). Also having a preview for the arguments and transient data.
- Transient data could take a table type format
- Be able to group peers and target private data collections (something that could be done in advanced options)
- The tabs for recent and saved look like they are headings for the transaction name and time stamp:
Recent                      Saved
createPenguin         [09/10/19 11:10:00]
- Add notification to confirm transaction has saved
- Submit/evaluate phrasing: take it back to 'create new transaction'. Although this does sound like creating a new type of transaction, because of the context it is better than 'submit/evaluate transaction' as it looks like you're about to resubmit an existing transaction.
- Evaluate/submit buttons should be under the form
- Have a button for resubmitting last transaction
- Need to get example of output to format this properly: e.g. dividing the output into HTTP code and resulting json as they would like to be able to copy this output to be used in future transactions
- Have output filter as the output will likely be big for each transaction; able to find specific piece of info like 'HTTP code'
- Show result of each peer after transaction: if certain peers should be rejecting the transaction because they're not in the targeted pdc, this would be useful to see.

I'll start acting on this on Monday.

**Comment by Charlotte8699** [comment]
**An update on how the hi fis are coming along.** 
- The 'remove set' next to set 1 is just a reminder to add it in for set 2, the user wont be able to remove set 1.
- Still unsure where to put 'switch smart contract'
- Transaction output will be changed to get rid of the 'show less' and 'copy' buttons, it will just be an area you can scroll on.

Any comments are welcome!

![Screenshot 2019-11-11 at 10 24 28](https://user-images.githubusercontent.com/52786879/68580050-7212c300-046d-11ea-9bc8-30fb992b0296.png)

**Comment by Charlotte8699** [comment]
The latest styling of the transactions view

![Screenshot 2019-11-27 at 15 09 36](https://user-images.githubusercontent.com/52786879/69735178-32fc9700-1128-11ea-8c86-982f04c2d09e.png)
![Screenshot 2019-11-27 at 15 09 51](https://user-images.githubusercontent.com/52786879/69735189-36901e00-1128-11ea-924e-c8f086a583b1.png)

**Comment by Jakeeyturner** [comment]
Closing - this works has been completed.
