### ISSUE TITLE
A developer can import a package to the package view

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#13]
A button on the package view that lets you select a folder to add to the package view (later this will be an actual package)

From the current low-fis:

![image](https://media.github.ibm.com/user/3443/files/8631e6f2-754b-11e8-88b2-6895fb8fa964)

**Comment by caroline-church** [comment]
moving out of phase 1 as this won't get done in time

**Comment by m-g-k** [comment]
FYI, would be useful if an "imported" package could be "expanded" into the editor so you could look at the source and maybe even edit it before repackaging and deploying...

**Comment by davidkel** [comment]
From a support point of view this would be a really useful feature to help customers. A Customer can send their cds file and it can then be viewed in the tooling to look at the contents of the smart contract as well as determine the presence of a shrinkwrap.json file.

**Comment by caroline-church** [comment]
this issue should just cover importing a cds file. We shouldn't expand a package as it doesn't make sense, like you can't expand a jar file into an eclipse project

**Comment by m-g-k** [comment]
Actually, I disagree to some extent :-). A JAR file cannot be expanded because it's compiled bytecode, but a cds file will contain source and showing that (maybe as a preview only) would be helpful to users for lots of reasons like Dave mentioned above. I'm not bothered about being able to edit and repackage as I agree that's probably too far, but a allowing read only view of the source is different, given you have it available, seems helpful.
