### ISSUE TITLE
Use with Sublime Text??

### ISSUE THREAD

**Issue by GR899** [IBM-Blockchain/blockchain-vscode-extension#1317]
## Description
For those of us with an aversion to all things MS -- can this repo be used with Sublime Text or another IDE ***other than VS Code*** ? 

## Expected Behavior
Anything but VS Code

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version: NO - Sublime Text
* Environment name and version:  Node.js v8.9.4, npm v6.10.2
* Operating System and version: 10.14.6

**Comment by amanali1896** [comment]
I do not think that you have an extension for sublime text -- Especially by IBM. Since, nothing has been mentioned in the documentation. I think the only option you have, if you are running sublime text is, to install all the fabric's dependencies and prerequisites individually and then use it in sublime text. 

But if you do that, then you will not be able to take the advantage of the seamless workflow this extension has to offer. 

Hope it helps. :)

**Comment by Jakeeyturner** [comment]
Hi @GR899,

This extension only works with VS Code and we're not planning on developing extensions for other IDEs at this moment in time.

Thanks,
Jake
