### ISSUE TITLE
As a user i can see what files are in my cds package

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1382]
From the extension i want to be able to see what is inside a cds file so i can determine if there are unwanted files in there or files missing.

**Comment by EdMoffatt** [comment]
Adding some context so that someone can pick this up next week :)

CDS files may be created from open projects in the extension, or imported (a developer could be sent a CDS file by someone else). Either way, it'll then appear in the "Smart Contracts" panel in the Blockchain view:

![image](https://user-images.githubusercontent.com/7454304/65687690-aec36000-e061-11e9-9ae8-e91dd353bac4.png)

The developer is then most likely going to try installing/instantiating that CDS package on an environment like the Local Fabric Network next. If it's missing some stuff for whatever reason, that might fail, so we'd like them to be able to think "this CDS file doesn't work - I wonder if it's missing some required files", so there needs to be some action to "peek into" the CDS (which is like an archive format).

It's also possible that the CDS works fine but contains stuff it shouldn't. Perhaps hover info about the size (MB) would help a dev identify if this might be the case ("That CDS is a very large file, I wonder why?"). Probably a similar action in this case.

With than background, hopefully @Charlotte8699 can take a look at this one next week!

**Comment by Charlotte8699** [comment]
I've started looking into this today, I will have a chat with Caroline's team and Liam about their experiences with this type of file in VS code and then create a first round of mock ups later today/tomorrow.

**Comment by Charlotte8699** [comment]
I've had a look at this issue and thought of a few ways of indicating to a user whether they've got too many files/too little in their CDS package.

The main issue i've found is that it isn't possible to tell which files are included in the CDS file if the smart contract was packaged outside the extension. The set of low fi initial mock ups below show how the behaviour could be different based on whether the files were packaged in the extension or outside of the extension. 

Link 1 - The smart contract was packaged through extension
Package smart contract   -->   list of files contained is displayed and automatically saved to the CDS package   -->   Left click on package to show basic info about file and to give the user the option to view file contents again in the output 
https://xd.adobe.com/view/48607478-3cff-45b1-66c0-833762a20f68-3e51/

Link 2 - The package was imported 
Package imported   -->   output lets the user know that there is limited file information if package is imported   --> still gives file size/number of files, but doesn't give user the option of view files
https://xd.adobe.com/view/8f13061f-cedb-45d4-5a24-d4e8fb58699f-f922/

**Comment by Charlotte8699** [comment]
Caroline gave me some feedback so I have reacted to this below. These two interactions will hopefully provide enough information to the user about their CDS file for them to tell whether they've got too many/too little files in their package.

**Hover interaction for the CDS file**
This shows the file size and number of files so the user can quickly make a judgement about whether there are too many/too little files and whether the file size seems off.

![Screenshot 2019-10-22 at 15 56 18](https://user-images.githubusercontent.com/52786879/67299368-7db14080-f4e4-11e9-94be-c40afaff4406.png)

**Right click on the CDS file**
Should giving the file size and number of files not be enough for the user, they can do the following to find out more info about the files.
The existing options for this are **Export package** and **Delete package**. I've added in a **View package information** which I was thinking would print the file information to the output so the user can see exactly what files are in their package, just as it appears when they first package the contract.

![Screenshot 2019-10-22 at 15 56 26](https://user-images.githubusercontent.com/52786879/67299379-830e8b00-f4e4-11e9-942e-ae34f99a93f0.png)

**Comment by Charlotte8699** [comment]
Update on these mock-ups with the v1.4 to v2.0 work (including Ed's recent mock ups on how to divide up the v1.4 packages with the v2.0 packages).

These take into account the file type (.cds and .tgz). On hover, the files will show what type of file they are while still showing the file size and number of files. Both will print the contents of the package to the output when right clicking the package and selecting 'view package information'.

![Screenshot 2019-11-20 at 11 13 35](https://user-images.githubusercontent.com/52786879/69234342-ccef9d00-0b86-11ea-8b05-401993291396.png)

![Screenshot 2019-11-20 at 11 13 45](https://user-images.githubusercontent.com/52786879/69234349-d2e57e00-0b86-11ea-8402-1f8e1bc4593d.png)

![Screenshot 2019-11-20 at 11 13 53](https://user-images.githubusercontent.com/52786879/69234358-d7119b80-0b86-11ea-8dcf-cf4b14ef5cc5.png)

**Comment by cazfletch** [comment]
done so closing
