### ISSUE TITLE
Duplicate environment disconnect buttons

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1445]
## Description

When I connect to an environment, delete a node and add a node, it takes me to the setup screen.
On this screen there are two 'disconnect from environment' buttons.

![Screenshot 2019-09-25 at 13 07 36](https://user-images.githubusercontent.com/10009752/65599375-9ede4a00-df95-11e9-8ca9-7009d239101b.png)
## Expected Behavior

I should only have each button once.
## Actual Behavior

I have two of the same button.
## Steps to Reproduce

1. Create an environment (where all the nodes are in a single file) 
2. Associate identities with each of the nodes
3. Connect to the environment
4. Delete a node
5. Add a node (select the file)

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

**Comment by cazfletch** [comment]
Now we have updated the minimum version of vscode we can use or in when clauses so we should update all the whens to have ors and remove ones not needed anymore in package.json

**Comment by erin-hughes** [comment]
Fixed as of #1469 

To test the fix for the duplicate disconnect buttons, follow the steps to reproduce the issue. There should only be one disconnect button now instead of two.

To test that the package.json has been updated correctly, right click all of the items that appear in the side panels on the left, and confirm that the options that appear as you would expect.
