### ISSUE TITLE
Unable to add an identity to the local fabric wallet unless already connected to environment

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1465]
If you try and add an identity to the local fabric wallet and you aren't already connected to the environment it will fail.

It should let you add an identity to a wallet even if you aren't connected

**Comment by erin-hughes** [comment]
The problem is in `addWalletIdentityCommand.ts` at line 83. 

Currently, if we're trying to add an identity to the local fabric wallet, we get the MSPid from the connection to the local fabric environment instead of asking for it. There's no code to handle getting the MSPid when we're not connected, which is why the command is failing.
