### ISSUE TITLE
Investigate multi-org gateway connection error

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1601]
## Description

> I'm facing problems connecting gateways to my running network. My network is built on the nodes file attached below: 4 peers, each in a different org, exposing ports 7051, 8051, 9051, and 10051 respectively.
>
> When I create and connect a gateway using an identity from the first org (peer 7051), everything works fine, and I'm able to see the channel as well as the contract on that channel.
>
> But when I create and try to connect a gateway using an identity from any of the other 3 orgs, I only get to the point where the channel name is obtained. The installed contracts can't be fetched, with an error like the following:
> 
> ```[10/31/2019 6:53:32 PM] [ERROR] Error getting instantiated smart contracts for channel tradechannel Failed to connect before the deadline URL:grpcs://localhost:7051```
> 
> Why is every gateway trying to hit 7051 (the first peer)? When I look at the connection file generated in ~/.fabric-vscode/gateways/xyz/connection.json, it has a different port (8051, etc.)

When passing `null` to `channel.queryInstantiatedChaincodes()` (https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/master/extension/fabric/FabricConnection.ts#L92) it will attempt to query the first peer (in the users scenario above, the peer on port 7051).

We need to investigate this further and decide if we should be passing in a value to this function.
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

**Comment by VRamakrishna** [comment]
I'm the one who submitted the original query. Here are my VSCode specs:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.4.0-166-generic
```
(Distribution is Ubuntu 18.04 LTS)

**Comment by VRamakrishna** [comment]
I'd like to report that I'm seeing the same behavior when I write a JavaScript application using the `fabric-network` npm package. Even though my connection profile explicitly states the peer URL to be `grpcs://<hostname>:8051`, the request always goes to `grpcs://<hostname>:7051` (I have 4 peers, listening on ports 7051, 8051, 9051, and 10051 respectively, each belonging to a different org.)

When I write an equivalent application in Java using `fabric-gateway-java`, I don't see this error. (Though I see a different error there; the ssl-target-name-override` parameter isn't getting respected.)

**Comment by cazfletch** [comment]
When you create a gateway from an environment you have to say which org you want to create it for. This means that you have to use an identity for that organisation. 

The ssl-target-name-override property is named host-target-name-override in the java sdk that is why it isn't been respected

**Comment by VRamakrishna** [comment]
@cazfletch As you say, the Java gateway needs a different parameter name, which I discovered a while ago thanks to someone on the Slack channel.

Sorry if my offhand comment about this parameter muddied the waters, but my original query still stands. Why does a gateway I create through the GUI, and using an identity from the organization I wish to associate it with, nevertheless always try to hit a single peer (the one with the lowest port number)?

Did you test this scenario and were unable to reproduce the error? If not, can I request you to reopen this issue and check it out?

Thank you in advance!

**Comment by bmilleker** [comment]
I am experiencing a similar issue. Not with the port, but with the hostname. I am receiving the error: _Error: Failed to connect before the deadline URL:grpcs://localhost:7051_. My connection profile does not mention or refer to localhost at all. I am not sure where that is coming from. 

I had a similar network setup months ago, and did not have these issues.

**Comment by cazfletch** [comment]
For the description it says you had 4 peers each in different organisations so you need to create a gateway for each organisation.

**Comment by VRamakrishna** [comment]
@cazfletch That's what I did. I had 4 peers, exposing ports 7051, 8051, 9051, and 10051 respectively. But every gateway I created (for each distinct organization, using a distinct identity provided by the CA of that organization) ended up trying to hit peer 7051, as I observed in the logs. Only one of them succeeded because my network had TLS enabled.

**Comment by cazfletch** [comment]
If that's the case it sounds like it could be a bug in the sdk. You should create a jira for it https://jira.hyperledger.org/projects/FAB/issues/FAB-17212?filter=allopenissues

**Comment by VRamakrishna** [comment]
Sorry, but when I tried some basic tracing, it seemed like the problem was in the extension code, which I reported on the Slack channel. You can see what I suggested in Jake's original comment above:

_When passing `null` to `channel.queryInstantiatedChaincodes()` (https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/master/extension/fabric/FabricConnection.ts#L92) it will attempt to query the first peer (in the users scenario above, the peer on port 7051).

We need to investigate this further and decide if we should be passing in a value to this function._

From what I know, the SDK supports specification of peer targets (and I used that feature in the past when I was developing apps directly with the low-level SDK), but that feature doesn't seem to be exercised by the extension. Unless I'm missing something here.

If you have a connection profile with multiple orgs and TLS enabled, this should be easy to confirm or reject. If it works for you, the mistake must be in my configuration and I'll try to debug further. Thanks!

**Comment by cazfletch** [comment]
I just tried to recreate this issue and i don't get any errors. I have to orgs and can create a gateway for each org and connect to it without any errors.

**Comment by VRamakrishna** [comment]
@cazfletch Then there must be something wrong in my setup. I'll debug further.

Thanks for indulging me, and I really appreciate your taking the time to verify the issue and respond.
