### ISSUE TITLE
Create extension status page

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#1643]
We should create a status page on the wiki or GitHub pages - this will let users know that there is a problem with the extension.

We could use something like [this](https://github.com/bisscomm/status), or something even simpler.

We should let the user know what the problem is, when it was identified, a workaround where possible and any updates on the progress of the fix.

We should create a button alongside 'Retry activation' in the extension, with a button to this status page. If something goes terribly wrong, the user can see the status of the extension.

**Comment by EdMoffatt** [comment]
When I visit the link and try to view the GitHub Pages site, I just get a 404 - same on the original repo that one was forked from.

Did you already show the page in show-n-tell? I feel like you did but I missed it! If not, maybe share next week? Or if you've already done it I could just come visit you to take a look at it!

In any case, I can get cracking on the design work for how you'd actually get there right away, so I'll add this to the current sprint.

**Comment by Jakeeyturner** [comment]
I think GitHub changed something - I've just forked it and got it working.
https://jakeeyturner.github.io/status/

**Comment by EdMoffatt** [comment]
To link to the page from the extension, as Jake suggested, lets add a button on the "Failed to load extension" notification, like so:

![image](https://user-images.githubusercontent.com/7454304/71981629-ae1e9600-321a-11ea-93e3-2e04ab946bea.png)

It would also be nice to put something on the homepage, so that even if the extension works but there's smaller issue that a user might want to be made aware of, Just a rough idea for now, but something like:

![image](https://user-images.githubusercontent.com/7454304/71981716-d908ea00-321a-11ea-9cee-774a0b44cd0a.png)

**Comment by cazfletch** [comment]
done so closing
