### ISSUE TITLE
As a user i can distinguish between different types of environment

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#2023]
We have different types of environment we should add an icon or something to show which type they are

**Comment by cazfletch** [comment]
We should also add info so that the user can see info about the environment on hover such as the url of the ops tools etc

**Comment by EdMoffatt** [comment]
Designs for icon usage and organisation of things into "folders"...

![image](https://user-images.githubusercontent.com/7454304/77893235-91b75600-726b-11ea-9eb8-cb54532eabe8.png)

Some extra thoughts from Simon: 

> I was chatting to Simon who suggested having “IBM Cloud” as a separate section under Environments because then if they’re not logged in we could offer a fake tree item of “+ Log in to IBM Cloud” and if they’re logged in but no instances we could have “+ create new instance” which launches the a web browser to the catalog page for the IBP service.

We'd do that (and indeed add the "IBM Cloud" section I guess) one we actually have the ability to log in to IBM Cloud tho

**Comment by Charlotte8699** [comment]
Putting the full amount of feedback on this panel from Simon in here

### Already covered in this issue
I believe the following are being addressed by the designs above and Erin (@erin-hughes can you please confirm/deny?)

- No environments folders 

- The gateway not in an environment doesn't look good – the environment (microfab) looks like a child feature of the gateway not in an environment

![Screenshot 2020-04-22 at 12 04 28](https://user-images.githubusercontent.com/52786879/80472358-845dbc00-893c-11ea-8ea8-7dee21e2d601.png)

- Have way of sorting gateways/wallets that aren't in an environment e.g. "Other gateways"/"Other wallets"

- Give the environments an icon – folders

### Additional points not yet addressed

- No dropdown for single gateway is confusing
Is this because for more than 1 gateway, they're going to be put into a folder (screenshot 1), where as a single gateway (screenshot 2) isn't? I don't know if i've understood this or not.

Screenshot 1;
<img width="235" alt="Screenshot 2020-04-28 at 10 46 39" src="https://user-images.githubusercontent.com/52786879/80473227-bfacba80-893d-11ea-8af1-d3fde624e98e.png">

Screenshot 2;
<img width="164" alt="Screenshot 2020-04-28 at 10 46 45" src="https://user-images.githubusercontent.com/52786879/80473239-c3404180-893d-11ea-8200-a0e11506201a.png">

**Comment by erin-hughes** [comment]
@Charlotte8699 Yep, I can cover the feedback as a part of this issue

Also, you're right about the issue with not having a dropdown for a single gateway - currently we only put the gateways into a dropdown if there's more than one of them belonging to the same environment

**Comment by Charlotte8699** [comment]
### Folders redesign - feedback request

The screenshots below show the panel with and without expanded sections

If anyone gets 5 minutes to review this, I would very grateful. I would like feedback on the following;
- **How a 1 org gateway and wallet looks in a folder when expanded**
- **Icon choice for a gateway and wallet without an associated environment:** Could we just have the gateway/wallet symbol here? or is there a better icon anyone can think of?

Screenshot 1 - Initial panel
<img width="236" alt="Screenshot 2020-04-28 at 15 27 37" src="https://user-images.githubusercontent.com/52786879/80499405-d9adc380-8964-11ea-82e6-d32e8dc4a62a.png">

Screenshot 2 - Expanded panel
<img width="233" alt="Screenshot 2020-04-28 at 15 27 45" src="https://user-images.githubusercontent.com/52786879/80499414-dc101d80-8964-11ea-8898-790086c3e68d.png">

@erin-hughes @EdMoffatt

**Comment by EdMoffatt** [comment]
Heading in a good direction :) Few feedback points...

1. I can't work out how the Gateway folder names are derived from the environment names. I think we need a mockup where the names match up. I know this wasn't the case on my original mockup, but since this one needs to be precise, it needs some more attention to detail :) e.g. Microfab shows in gateways as if it's an Environment, but it's not on the environments list. Also, why is it "1 Org local Fabric" on the environments list and "1 Org local Gateway" on the gateways list? A rule that says "remove "Fabric" from the end of the environment (if it's there) and add "Gateway"" doesn't seem like a good rule for determining folder names in the Gateway panel. I think I'd expect to see that folder still called !1 Org local Fabric" in this example.

2. Ah, similar thing I guess :) Under wallets, I think that first folder should be "1 Org local Fabric" if that's the name of the environment. That thing is a collection of wallets, not a wallet itself, so calling it "Wallet" doesn't sit right with ne.

3. Where do the names "Gateway without env." and "Wallet without env." come from? IS that what the user has named that gateway or wallet? What if there are multiple gateways, for different networks, none of which have an associated gateway - do they all get grouped into one folder, or do they each get their own folder?

I think matching up the names will go a long way to helping make this clearer :)

**Comment by Charlotte8699** [comment]
### Updated!
- Made the names match up
- Changed the names of the gateways/wallets without an environment. I _**think**_ the names of these gateways/wallets would be provided by the user but i'm not certain. I'll see what Erin says!
- I've done it so each network not associated with an environment has its own folder - again, i'm not certain this is what's best, but i'll see if Erin has any comments.

<img width="465" alt="Screenshot 2020-04-28 at 16 08 21" src="https://user-images.githubusercontent.com/52786879/80503967-7d4da280-896a-11ea-9119-4f8f253256d2.png">

**Comment by EdMoffatt** [comment]
This is looking great Charlotte :) Only thought is what do the noenvironment ones look like when expanded out? I think we might want to not have an icon on the folders, as I'm expecting there will then be for example a gateway inside the noenvironment_1 folder (which will have that "2 people" ("organization") icon on it) - and having the same icon on the thing and on the folder containing the thing I feel will look odd

**Comment by Charlotte8699** [comment]
I was thinking that, but i thought it might look a bit strange without an icon there - i've got rid of the icon here;
<img width="469" alt="Screenshot 2020-04-29 at 09 27 27" src="https://user-images.githubusercontent.com/52786879/80575531-a702da00-89fb-11ea-9d2e-a96223b22f14.png">

If we were going to use an icon to suggest that the 'environment is undefined' - what might this be? so we would need an icon to go in the places with the black boxes;
<img width="340" alt="Screenshot 2020-04-29 at 09 27 00" src="https://user-images.githubusercontent.com/52786879/80575647-d31e5b00-89fb-11ea-8b45-e3555ceb90c2.png">

I don't mind it too much without the icon now i've seen it - what do you think?

Also, when expanded, do gateways/wallets without an associated environment have the same folder structure as I've suggested in the mock up above?

**Comment by EdMoffatt** [comment]
Personally I like it without the icon - it helps suggest there's something different about that "folder", and the icon that represents "what type of environment is this related to" is blank because there's no associated environment. Feels like if we put an icon there it looks like that's some other type of environment, and actually you lose some of the information you could have read at a glance.

Structure of those expanded gateways and wallets looks spot on to me.

I believe when a user adds a gateway, we just get them to name the gateway. Not sure where the name "noenvironment_1" would come from, unless we're automatically setting it. Then it feels like if I named my gateway "Fabric BYFN" for example and it gets put in a folder called "noenvironment_3", it bothers me that unless I remember which order I created them in I feel I'd be opening up _1, _2 and _3 to try and find out which one contains the gateway for by BYFN network.

Unless we get the user to also name the folder (which feels like just inserting another step for little gain), we might be best off duplicating the gateway name as the folder name, such that the user knows which one to expand to find a particular gateway they're after?

**Comment by Charlotte8699** [comment]
Makes sense, but if they've got 2 gateways in the folder (Org1 Gateway, Org2 Gateway), what would we call it?

**Comment by EdMoffatt** [comment]
I think if they created "Org1 Gateway" and "Org2 Gateway", they'd get 2 separate folders. We've got no way of knowing whether those 2 gateways connect to the same network or not.
So I figure if you're not got the environment and you didn't create the gateways from the environment (instead you added them yourself) then they'd always be loners :(
I wonder if we're identifying a use case for a user to create their own folders after all in that case. If you've got 4 gateways that you know point to the same network, it'd be pretty useful to be able to put them together in a folder. Hmmmm. Might be worth seeing what Simon thinks on this one, whether that's something he can see himself doing!

**Comment by Charlotte8699** [comment]
I have a couple of questions here;
1. What if the user tries generating a gateway without an environment with the same name as another without an environment? Would they be told to choose a different name, or would it be on them to make sure they choose a sensible name so they don't end up with 2 'Org 1 Gateway's in the 'Other gateways' folder?
2. Similar to above, but how would wallets work here when the user wants more than 1 lot of wallets in there, but the generated wallets are the same?
3. Is 'Other gateways'/ 'Other wallets' the best phrasing? I was mimicking what they've got above with 'Other networks'

<img width="679" alt="Screenshot 2020-04-30 at 12 46 40" src="https://user-images.githubusercontent.com/52786879/80706770-c45da400-8ae0-11ea-9f5d-c0f919a50fae.png">

**Comment by erin-hughes** [comment]
We don't let people create multiple gateways with the same name, same with wallets and environments. We'll just throw an error to tell them there's already an entry with that name.

**Comment by Charlotte8699** [comment]
Okay so that's questions 1 and 2 sorted!

Do we think 'other gateways'/'other wallets' is the best phrasing? and is there any final feedback?

@EdMoffatt  @erin-hughes

**Comment by cazfletch** [comment]
done so closing
