### ISSUE TITLE
As a user i want to export application data

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#2220]
As a user i should be able to export all the data required to more easily create an application. We should export this data as a file so it can be consumed by others

Below is an example of the format

```
FABRIC_CONNECTION_PROFILE={"certificateAuthorities":{"Org1CA":{"caName":"ca","url":"http://172.19.0.3:17050"}},"client":{"connection":{"timeout":{"orderer":"300","peer":{"endorser":"300"}}},"organization":"Org1MSP"},"name":"Org1","organizations":{"Org1MSP":{"certificateAuthorities":["Org1CA"],"mspid":"Org1MSP","peers":["Org1Peer1"]}},"peers":{"Org1Peer1":{"url":"grpc://172.19.0.4:17051"}},"version":"1.0.0"}
FABRIC_WALLET_PROFILE={"type":"IN_MEMORY"}
FABRIC_WALLET_CREDENTIALS=[{"cert":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXVENDQWYrZ0F3SUJBZ0lVTVQwa2JuZlRnaFR1S1MvS2RySkI5YjU2ZlZFd0NnWUlLb1pJemowRUF3SXcKZnpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNURFZOaApiaUJHY21GdVkybHpZMjh4SHpBZEJnTlZCQW9URmtsdWRHVnlibVYwSUZkcFpHZGxkSE1zSUVsdVl5NHhEREFLCkJnTlZCQXNUQTFkWFZ6RVVNQklHQTFVRUF4TUxaWGhoYlhCc1pTNWpiMjB3SGhjTk1qQXdOREUxTVRjME9UQXcKV2hjTk1qRXdOREUxTVRjMU5EQXdXakJkTVFzd0NRWURWUVFHRXdKVlV6RVhNQlVHQTFVRUNCTU9UbTl5ZEdnZwpRMkZ5YjJ4cGJtRXhGREFTQmdOVkJBb1RDMGg1Y0dWeWJHVmtaMlZ5TVE4d0RRWURWUVFMRXdaamJHbGxiblF4CkRqQU1CZ05WQkFNVEJXRmtiV2x1TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZEZ0ZEZTVk4KcXd3TGU1ajZRMVVqd056eXhGbXpuK3pTbzRGbEZFdVplR0FJZER0OGQwcENjLytxRFNCZlB4SVREeEpONWt5ZAo2bHdhTmoxYnFObHhDYU43TUhrd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEClZSME9CQllFRkdGTEZPWUJJdWNBRGFTRHk3emdadm5IZWJKak1COEdBMVVkSXdRWU1CYUFGQmRuUWoycW5vSS8KeE1VZG4xdkRtZEcxbkVnUU1Ca0dBMVVkRVFRU01CQ0NEbVJ2WTJ0bGNpMWtaWE5yZEc5d01Bb0dDQ3FHU000OQpCQU1DQTBnQU1FVUNJUURkUFpsajJ3KzBZdXArV1JxSEtNaWI4QmdJdHg5VTBLVk9rUGlveHVtSnhnSWdmQi9iCnVpbFl4d3RXMUN0bENLYXY1Z29pWnRhbHEzbi9hbHpVbVpSMjRqTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==","msp_id":"Org1MSP","name":"admin","private_key":"LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3FCNHBRNE5PRFZzT2RMR2MKYWxSM3NCcm9WM095aSs2MGpDdVpZK001blF1aFJBTkNBQVIwVzEwVkpVMnJEQXQ3bVBwRFZTUEEzUExFV2JPZgo3TktqZ1dVVVM1bDRZQWgwTzN4M1NrSnovNm9OSUY4L0VoTVBFazNtVEozcVhCbzJQVnVvMlhFSgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t"}]
FABRIC_CHANNEL=mychannel
FABRIC_CONTRACT=myasset
FABRIC_DEFAULT_IDENTITY=admin
```

**Comment by chilanti** [comment]
A few comments:
1) The connection profile must include the host names or the ip addresses of the peers and the CA. As exported using the VSCode command (from the palette), the connection profile JSON references those servers with `localhost` - which wouldn't work once the client app is containerized.
2) The "wallet profile" can be a constant, with its value as in the example.
3) We'd like to have some design discussion on how channel, contract, and fabric identity can be injected.

**Comment by jorgedr94** [comment]
Hi @cazfletch :

@chilanti  and I had a talk about this requirement so I want to summarize the full requirement here for clarity.  In general we believe that all the information we need can be obtained from the Fabric Gateway defined in the VSCode extension.   In particular, once the user drills down to a particular smart contract in the Fabric-Gateways section,  you will have all the information that needs to be exported.  See image below:

![image](https://user-images.githubusercontent.com/25494074/80414668-6130ff00-889f-11ea-8f98-f601d747b731.png)

Our requirements are as follow: 

1.   As stated above, we need the IBP VSCode extension to provide a way to export the data that is required for an application to communicate with a Fabric network.
2. The information should be exported as a file.   The format of the file should be that of a properly file where the name of the properties are capitalized.
3. The user should be able to export the file in what ever directory they want. 
4. The default name of the file should be `env.properties` but the user should be able to overwrite the default name. 
5.  The information that we need is the fabric connection profile, the Fabric credentials used to communicate with the network,  the name of the credential being used, the name of the channel to use and the name of the smart contract to connect to (FABRIC_CONTRACT). 
6.  The name of the variables in the file are negotiable but here are the ones we are suggesting:
    ```
    FABRIC_CONNECTION_PROFILE
    FABRIC_WALLET_CREDENTIALS
    FABRIC_DEFAULT_IDENTITY
    FABRIC_CHANNEL
    FABRIC_CONTRACT
    ````
7.  The value for the `FABRIC_CONNECTION_PROFILE` should be the JSON object that describes a Fabric network as generated by the "Export Connection Profile" option in the Fabric Gateways section.   An example of a connection profile is as follows:
    ```
    {
        "certificateAuthorities": {
            "Org1CA": {
                "caName": "ca",
                "url": "http://ca.org1.example.com:17070"
            }
        },
        "client": {
            "connection": {
                "timeout": {
                    "orderer": "300",
                    "peer": {
                        "endorser": "300"
                    }
                }
            },
            "organization": "Org1MSP"
        },
        "name": "Org1",
        "organizations": {
            "Org1MSP": {
                "certificateAuthorities": [
                    "Org1CA"
                ],
                "mspid": "Org1MSP",
                "peers": [
                    "Org1Peer1"
                ]
            }
        },
        "peers": {
            "Org1Peer1": {
                "url": "grpc://peer0.org1.example.com:17071"
            }
        },
        "version": "1.0.0"
    }
    ```

8.  The value of the `FABRIC_CONNECTION_PROFILE` should be contained all within the same line.   That is, the value for `FABRIC_CONNECTION_PROFILE` should not have new lines in it.  All of the profile should be contained within the same line.   Empty spaces can also be removed. 
9.  For local Fabric networks, all endpoints referenced in the `FABRIC_CONNECTION_PROFILE` JSON object should use the FQDN from the point of view of the Docker network where Fabric is deployed as opposed to `localhost` which is the endpoint to connect to if the connection is coming from outside of the Docker network.   For example `"http://ca.org1.example.com:17070"` should be generated when referring to the local Fabric CA deployed on the Docker network instead of `"http://localhost:17070"`
10.  The value for `FABRIC_WALLET_CREDENTIALS` should represent an array of Identity JSON objects. The reason for the array format is so that we can inject multiple identities to the application if needed.   For example:
   ```
     FABRIC_WALLET_CREDENTIALS=[{identityJSON1}, {identityJSON2}]
   ```
The JSON object that represents the Identity should have the following fields (this is the standard used by the IBP VSCode Extension anyway):
  ```
   {
        "cert": "base64encodinghere",    
        "msp_id": "Org1MSP",    
        "name": "admin",    
        "private_key": "base64encodinghere"
    }
  ```
11.  The value of the `FABRIC_WALLET_CREDENTIALS` should be contained all within the same line.   Empty spaces can also be removed.     
12.  The identity to export into `FABRIC_WALLET_CREDENTIALS`  should be the identity that is being used by the Fabric Gateway to connect to the network.  
12. The value of the `FABRIC_DEFAULT_IDENTITY` variable should be the name of the identity exported as specified in the `name` field of the JSON object.  For example:
  ```
   FABRIC_DEFAULT_IDENTITY=admin
  ```
13.  The value of the `FABRIC_CHANNEL` variable should be the name of the channel the gateway is connected to. For example:
  ```
   FABRIC_CHANNEL=mychannel
  ```
13.  The value of the `FABRIC_CONTRACT` variable should be the name of the smart contract selected by the user or specified by the user is exporting the connection information.  For example:
  ```
   FABRIC_CONTRACT=myasset-cc
  ```

**Comment by EdMoffatt** [comment]
Here's what I'm thinking for the flow of how we would add this in to the extension:

[Client App asset export.pdf](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4609144/Client.App.asset.export.pdf)

(Wording and naming of things I'm totally happy to change, this is just my first bash at something!)

**Comment by jorgedr94** [comment]
@cazfletch Our team verified the test version of the extension and it works very nicely.   They tested with a local configuration and with a remote config and both worked well and made our application work out of the box.
