### ISSUE TITLE
Associating wallet with multiple environments bug

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#2354]
## Description

In our v1.0.29/v1.0.30 release we accidentally introduced a bug whilst implementing the gateway & wallet icon changes.

To recreate:
- Create a SaaS/Cloud environment (env1)
- Create a new wallet (wallet1) and associate identities with env1
- Create another SaaS/Cloud environment (env2)
- Associate identities in wallet1 with env2
- Connecting will fail

To fix:
- Create/use a different wallet when creating a new environment

## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

**Comment by erin-hughes** [comment]
The problem is that in order to show a wallet being used for an ops tools environment in the right group, we're assigning it a `fromEnvironment` property. Then when you associate the identities in that wallet with a second ops tools environment, that property doesn't get updated because we already have a `fromEnvironment`, so the code freaks out when you try to connect.

We could either:
1. Stick all the ops tools wallets in the 'other wallets' group and not try to classify them in the tree, or
2. Update the wallets so that they can be associated with multiple environments

If we go for option 2, that raises the question of where in the tree we should put a wallet that's been associated with multiple environments. Should we put it in the groups for each of those multiple environments, or put it in a different group altogether?

@EdMoffatt could use your input on this! 🙏

**Comment by EdMoffatt** [comment]
This might be a dumb suggestion, but what about if we renamed the "Other Wallets" category to be "Other/Shared Wallets"? Then if a wallet is associated with a single environment, we classify it according to the environment type, and then only if you associate it with 2 environments do we then go "ok, nope, sorry, we're just gonna have to put that in the bucket category".

Not sure if I'm understanding it correctly, but that's my initial thought!

**Comment by sstone1** [comment]
+1 to the suggestion from @EdMoffatt, I suspect this is not going to be a common use case so let's do the easiest thing for now
