### ISSUE TITLE
As a developer I want to delete multiple packages in one go from the tree

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#278]
delete more than one package at a time. This is going to be more useful once we do packaging as an automated step either in instantiate or debug

**Comment by EdMoffatt** [comment]
My starter for 10 is that since you can already left-click an existing package to highlight it, we should support shift-click and ctrl/cmd-click to multi-select, and then on right-click have "Export Package / Delete Package" if you've got one selected, or "Export N Packeges / Delete N Packages" if N != 1 ;)

Multiple-export may be a silly addition that I've just accidentally added in there ;)

**Comment by Jakeeyturner** [comment]
Not sure shift-clicking on treeitems is possible yet - https://github.com/Microsoft/vscode/issues/56344
