### ISSUE TITLE
2.0.0-rc1: Evaluating a transaction in the transaction view doesn't use the selected peers

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/blockchain-vscode-extension#2907]
the gateway implementation uses a query plugin concept and I am assuming that the default SINGLE is being used by the extension. That means that it will lock onto a peer in the organisation of the identity making the request which means that selecting peers is not possible.

This is especially noticeable if I want to test private data

- I have 2 orgs and org 1 has a private collection
- I Submit a transaction to org1 to write to the private data as an org 1 identity
- I then want to evaluate that as an org1 identity but notice I can select which peers to send the request to so I choose a peer in my org
- I then want to make sure that peer2 org can't see the data and given I have the option to select a peer in that org for evaluation, do so and find I get back the private data

This is because the peer that's actually queried is a peer in my org that has the data.

The transaction view also implies that I can attempt to evaluate on multiple peers concurrently, but it won't.

This is because the extension is using evaluate transaction on the gateway api and the peer selected is actually going to be driven by the selected query strategy. Unless the extension has a way to explicitly set the peers to be queried, then the panel is confusing because it makes users think it's possible to select peers on an evaluate when that's not the case.

**Comment by lquintai** [comment]
**At the moment it is not possible for a user to select the peer for a given transaction to be evaluated, while already connected to a gateway, using the node SDK.**
The reason for this implementation in the SDK is that the client application developer should not have to worry about individual peers - that’s an operational concern.

To change the peers evaluating a transaction we need to create a custom query handler, which needs to be setup at connect time - it is part of the gatewayOptions.

What this means is that, if we were to use a custom query handler, in order to enforce it we would have to disconnect and reconnect to the gateway et least every time the target peers change, and disconnecting from a gateway closes the transaction view (this is still, I believe, a desired behaviour).


There are 2 options:
1. Inform the user that evaluate only occurs on a peer from the Org from which an identity was used to connect to the gateway. Perhaps prevent somehow the user from choosing a peer?
2. Try to enforce user selected peers on evaluate, and change the flow to allow for disconnect and recoonect without terminating the transaction view and losing information.
