### ISSUE TITLE
Errors about deploying chaincode

### ISSUE THREAD

**Issue by SipengXie** [IBM-Blockchain/blockchain-vscode-extension#2983]
I tried using the sample chaincode  of the go version, but failed many times.
The error information of VsCode is as followed
`Failed to install on peer Org1 Peer with reason: Could not install smart contact received error: failed with status:500 ::failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: external builder failed: external builder failed to build: external builder 'golang' failed: exit status 1`

**Comment by james-wallis** [comment]
I've tried to recreate this on V2.0.2.
I was able to:
* Generate a Go Smart Contract and package it (V2/.tar.gz) (I guess this is what you mean by `sample chaincode of the go version`?)
* Deploy it onto a local fabric environment
* Submit a `CreateMyAsset` transaction and  perform an evaluate query on `ReadMyAsset`

@SipengXie can you provide more information on your environment and the steps you've taken to use the sample chaincode? It would also help if you attach the sample chaincode so that I can test it locally.
