### ISSUE TITLE
Hyperledger Java Gateway 2.2.1 gives 404 NOT FOUND error when connecting to local IBM BC

### ISSUE THREAD

**Issue by FrankWang-LH** [IBM-Blockchain/blockchain-vscode-extension#2986]
## Description

I've been trying to work with Hyperledger Fabric with IBM VSCode Plugin. Recently after I upgraded the plugin to support Hyperledger v2, the application stopped working with a few errors, and I'm having trouble understanding why these happen.

## Expected Behavior

Should not produce any error.

## Actual Behavior

The first error I get is:
  `[main] ERROR org.hyperledger.fabric.sdk.ServiceDiscovery - Service discovery in channel: mychannel, peer: Peer{ id: 2, name: org1peer-api.127-0-0-1.nip.io:8080.......`
which seems weird as it's declaring discovery which doesn't seem to be an error.

The second error I get is:
  `[main] ERROR org.hyperledger.fabric.sdk.Channel - Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: ........gRPC failure=Status{code=UNIMPLEMENTED, description=HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,content-type=text/plain; charset=utf-8,date=Mon, 01 Mar 2021 05:04:34 GMT,x-content-type-options=nosniff,content-length=19)`
and on the blockchain console, I get a `"proxy error, client disconnected"` message.

which I also does not understand as I'm passing in the same arguments as I did before with HLF gateway & chain 1.4

## Steps to Reproduce
1. deploy any smart contract on a 2 org local fabric network setup with the VSCo extension.
2. try to use farbic gateway to connect and get contract, and everything seem to work until this step.
    e.g. `Wallet wallet = Wallets.newFileSystemWallet(walletPath);`
            `Gateway.Builder builder = Gateway.createBuilder();`
            `builder.identity(wallet, "Org1 Admin").networkConfig(networkConfigPath).discovery(true);`
           ` try (Gateway gateway = builder.connect()) {`
               `    Network network = gateway.getNetwork("mychannel");`
               `    Contract contract = network.getContract(contractName);`
               `    ...`
3. Submit a transaction request, e.g. `contract.submitTransaction("changeCarOwner", key, owner);`

## Existing issues
Not sure, haven't found any online.

## Your Environment
* IBM Blockchain Platform Extension Version: 2.0.2
* Hyperledger Fabric Java Gateway SDK: 2.2.1
* Visual Studio Code version: 1.52
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Java 1.8&15 (tried both)
* Operating System and version: Windows 10
* Link to your project: /

**Comment by lquintai** [comment]
Hi @FrankWang-LH 

I tried to recreate and didn't see the problem you mentioned.

Here is what I did:

1. Created a new 2 org network with IBM Blockchain Platform Extension Version 2.0.2
2. Created a default java contract with 'create a new project'
3. Deployed this contract on my network
4. Autogenerated functional tests (in the gateway panel -> Org1 Gateway -> my channel -> myContract -> right click and select 'Generate tests for smart contract' )
5. The autogenerated tests use fabric-gateway-java:2.2.0 by default so updated build.gradle to use 2.2.1 instead
6. Run the tests with `./graldew test` - and they run without errors. Since JUnit will run the tests in a random order the tests might fail (for example trying to delete an assert before creating the asset) but they still run.
7. I then realised you use contract methods to submit/evaluate so I also modified a couple of tests to use contract methods instead of transaction method. These tests still run.

For example, I changed this:
```
            Transaction transaction = contract.createTransaction("updateMyAsset");
            byte[] response = transaction.submit(args);
``` 
To this:
```
            byte[] response = contract.submitTransaction("updateMyAsset", args);
```


Might be worth it having a look at the autogenerated tests to see if you can spot something different from how you are doing things.

You also mentioned this was working before, were you using the beta version of the extension?

If the problem persists please let us know and add some more information.

I'm on VSCode 1.53.0, running Node v12.19.0.

**Comment by FrankWang-LH** [comment]
I tried `submitTransaction` before but it does not work. I currently rolled back to v1.0.40 and everything works so far. v2.0.2/v2 beta both didn't work for me.

**Comment by lquintai** [comment]
Hi @FrankWang-LH 

So I've tried this again, this time from a simple java app, and was able to recreate it that way!! 😅 

Here is the problem: **discovery as localhost has to be set to false in microfab environments** (used by the version 2 of the extension). The reason being that there is only one docker container for the whole network, and even though the peers have different DNSs, if discovery as localhost is used they will be assigned the same port on localhost, resulting in 404 when trying to submit a transaction.

It's not mentioned in the issue, but I'm assuming you are setting discovery as localhost as true. So if in your app you set discovery as localhost to false, this should be enough to get it to work.
```
import org.hyperledger.fabric.sdk.helper.Config;
        ...
        System.setProperty(Config.SERVICE_DISCOVER_AS_LOCALHOST, "false");

```
If this solution doesn't solve the problem, please reopen the issue and we will look into it.

**Comment by FrankWang-LH** [comment]
Thank you! I'll have a look at it tomorrow.
