### ISSUE TITLE
blockchain.ext.directory doesn't get written to user settings on Windows

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#308]
When James installed 0.0.5 on his Windows VM, the blockchain.ext.directory isn't in the user settings. When he packaged his smart contract, it writes it to the correct place: `C:\Users\james\.fabric-vscode` so we don't see any error saying that it's failed to write that user setting. When James adds it and edits the default, it can correctly package to that directory. So the getConfiguration api is finding the default from somewhere, but it should appear in the user's settings so they can edit it themselves

**Comment by sstone1** [comment]
This is, IMO, working as designed. The defaults are coming from the defaults in package.json, and they only appear in settings.json when the extension changes them or the user changes them. This is consistent with other extensions, and it works the same across MacOS and Windows.

People running/who have run the VSCode unit tests, will see that these settings do appear in settings.json with the default values. This is because the unit tests change the values for test purposes, and then change them back to the defaults. But normal users shouldn't see this.
