### ISSUE TITLE
As a developer I can create a contract through the ui

### ISSUE THREAD

**Issue by caroline-church** [IBM-Blockchain/blockchain-vscode-extension#432]
Currently there is no way to create a smart contract through the ui only a command

**Comment by EdMoffatt** [comment]
Observation from a few testers (Dave K, Matthew W, MGK) has been that they expect the "+" button on "Smart Contract Packages" to be the way of starting a new project, and try clicking that first.
It seems common for new users to install the extension, head over to the Blockchain view (as it's the new icon that appeared) and then look for some way of starting a new project.  So, I think we should...

1) Make the action to package an existing smart contract look less like a generic "Add" or "Create".  Maybe something that looks more like "Package"?

2) Add somewhere to click in the Blockchain view that will start a new project (i.e. same effect as running the command from the command prompt).  We could just leave the "+" there and have it do this since we know folks have been trying that instinctively!  Or we could do something else :)

**Comment by sstone1** [comment]
@EdMoffatt I like 2), my favourite video shows that the Azure Functions extension has a button for creating a new project as well: https://www.youtube.com/watch?v=0WE_wvimTO4

**Comment by caroline-church** [comment]
Agree with 1 and 2

**Comment by niv23** [comment]
After discussing with Ed, we have two ways to create a smart contract through the UI:

- The first idea, the user clicks the '+' icon to create a smart contract project and a new icon for package a smart contract project.
![1-1 icon for package a sc project](https://user-images.githubusercontent.com/44022961/50780717-95903e80-129b-11e9-8faf-59e8078fd50c.png)
- Clicking the '+' icon runs the command from the command prompt (Need to update the existing command prompt text).
![1-2 command triggered by clicking ui](https://user-images.githubusercontent.com/44022961/50780709-90cb8a80-129b-11e9-894f-601e8df62521.png)
- A few icon ideas for package a smart contract 
![package icons](https://user-images.githubusercontent.com/44022961/50780988-3da60780-129c-11e9-9ac6-1eab3aec3a86.png)

- The second idea, the '+' icon drops down into a list when clicked. The user can either create or package a smart contract. Creating a smart contract triggers the command prompt.
![2-1 left click icon and dropdown](https://user-images.githubusercontent.com/44022961/50780694-890be600-129b-11e9-92f0-d467c9b7d41a.png)
![2-2 command triggered by clicking ui dropdown](https://user-images.githubusercontent.com/44022961/50780695-890be600-129b-11e9-8f15-c049dc58e615.png)

**Comment by caroline-church** [comment]
i'm not sure if the second option is possible

**Comment by niv23** [comment]
Package icons (svg files)- [Package icons.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2741702/Package.icons.zip)

**Comment by Tobias-Hunter** [comment]
Before going on vacation wanted to drop in the icons for this & what we've had approved by the IBM Design team & the current IBM Design icons to replace the current ones to be more consistent across the extension, this will particularly helpful if icons are used into the tree view as they will be a similar style! 

![image](https://user-images.githubusercontent.com/25635381/51322960-ca03b780-1a5e-11e9-9ce5-8d64423f64d2.png)
.zip of the icons - [Icons.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2768896/Icons.zip)

**Comment by Tobias-Hunter** [comment]
Icons with the relevant colours for the dark & light themes

.zip of the icons for dark & light themes - [icons.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2803158/icons.zip)

For reference: 
- Light theme - #424242 
- Dark theme - #c5c5c5
