### ISSUE TITLE
Instantiating the basic contract one gets out of the box should not required specifying "instantiate"

### ISSUE THREAD

**Issue by lehors** [IBM-Blockchain/blockchain-vscode-extension#548]
The minimal contract one gets out of the box doesn't have any init function which makes instantiating it fail unless some other function name is specified, such as "instantiate".
I don't think this is user friendly.
Besides, the README section on Instantiate doesn't say one has to type "instantiate". The user has to get this from the screen grab, which is easily missed.

**Comment by caroline-church** [comment]
@lehors with the new programming model, the convention is to have the function which is called on instantiate be called instantiate (this can actually be any function, but we have chosen to make this the convention). Fabric however is defaulted to init and this cannot be changed until a major version if at all as it would break alot of existing applications. There are fabric jiras that are attempting to address this issue through the use of annotations to say which of your functions in your contract you want to be the instantiate function, this is not yet available though. 

The reason that the readme doesn't say you have to type instantiate is because as mentioned above the function to call on instantiate doesn't have to be instantiate it is just a convention.

**Comment by lehors** [comment]
I understand the challenge but following the README leads to a frustrating experience with an error trying to instantiate. Not a good UX.
Short of explaining all of the above in the README I think you could simply point out that to successfully instantiate the out-of-the-box smart contract one must specify the method to call, such as "instantiate" or carry an "init" function as a fallback.

**Comment by caroline-church** [comment]
closing as now you don't need to give a function name and nothing will be called
