### ISSUE TITLE
Upgrade Smart Contract does not work for remote connection

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/blockchain-vscode-extension#634]
## Description
Upgrade Smart Contract for remote gateway connection

## Expected Behavior
I should have been prompted to select package version to use for replacement

## Actual Behavior
The Upgrade Smart Contract option does not appear at all when you right click on an instantiated smart contract for a remote connection.

## Possible Fix
Fix to work as in previous versions

## Your Environment

* IBM Blockchain Platform Extension Version: 0.3.0
* Visual Studio Code version: 1.31.1
* Environment name and version (e.g. Node.js v8.11.1, npm v5.6):
* Operating System and version: Ubuntu 16.04.2 LTS
* Link to your project:

**Comment by caroline-church** [comment]
you can now only install, instantiate, and upgrade on the local fabric. Remote networks you cannot. This is because vscode is not meant for operational tasks and to make it have all the functionality you would want i.e. adding remote channels, peers etc we would essentially be replicating the operational UI.
