### ISSUE TITLE
Re-factor integration tests

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#695]
## Description
Our integration tests could be a lot more efficient. 

1. Use cucumber to run our integration (functional tests), links below
2. Or, try doing something like this with current mocha/sinon/chai framework:
- start with a clean local_fabric
- install/instantiate (probably the fabcar sample?) in the before bit of the tests (for set up) 
then have separate tests for:
- checking the tree structure
- upgrade
- generate tests
- submit transaction
- create identity
- stop/start/teardown etc
and others I'm forgetting

This should help solve our main problem of the integration tests taking too long to run, because most tests are instantiating a smart contract 

https://docs.cucumber.io/guides/overview/
https://sylvain.pontoreau.com/2018/04/30/typescript-cucumber-getting-started/

notes:
- we're now not testing the cert/private Key adding identity code anymore, after the addition of wallet code
- we should look into automagically running through our tutorials in our integration tests too

**Comment by Jakeeyturner** [comment]
Made a start in PR #982, however it still needs a fair amount of work.

- [ ] Create a contract
- [ ] Package a contract
- [ ] Install a package
- [ ] Instantiate a contract
- [ ] Update a contract
- [ ] Generate and run functional tests
- [ ] Submit a transaction
- [ ] Evaluate a transaction
- [ ] Transient data
- [ ] Check Local Fabric Ops panel tree items
- [ ] Identity actions
- [ ] Wallet actions
- [ ] Wallet association
- [ ] Gateway actions
- [ ] FabCar/Commercial Paper scenarios
- [ ] Fabric actions

I've probably missed something as there are a lot of things happening in our integration tests (including checking tree items).

For the time being, the Cucumber tests aren't running in Travis as the tests are taking a long time.
In a future pass, we should optimise these scenarios by using tags to have scenarios run in a certain order. We should re-use instantiated contracts in order to speed up the time our tests take.

I also believe that the features and steps could be better structured in a future PR, however currently I'm unsure of how so. I think that once we create more scenarios, then this will become apparent.

**Comment by heatherlp** [comment]
The work under #982 is good for a first pass, but it needs some tidying up including:
- [ ] removing any givens/then not used
- [ ] provide feature descriptions
- [ ] using tables in the feature files as and when

**Comment by cazfletch** [comment]
we should do the above comment in sprint 8

**Comment by cazfletch** [comment]
Do evaluate in sprint 11

**Comment by cazfletch** [comment]
sprint 13: fab car sample test

**Comment by cazfletch** [comment]
closing as done most of this. Can raise separate issues for new cucumber tests
