### ISSUE TITLE
[feature request] VSCode plugin should provide a 'deploy smart contract' command

### ISSUE THREAD

**Issue by Th1rstyGiant** [IBM-Blockchain/blockchain-vscode-extension#763]
Deploying a smart contract requires several steps using the vscode plugin. First you package the smart contract, then install it to a peer and then instantiate it on a channel. During development this process can be repeated several times and it would be useful to have a command that handles these operations for us.

This would also include bumping the version number of the smart contract so that we don't have to keep updating the version in `package.json` each time we install a smart contract and then have to remember to revert it before committing the code.

## Expected Behaviour
A single command to deploy a smart contract to the local fabric created by vscode code to aid with smart contract development.

## Actual Behaviour
As developers, we have to go through each step of the process ourselves to deploy a smart contract.

## Steps to Reproduce
1. Go through the deployment process

## Your Environment
* IBM Blockchain Platform Extension Version: 0.3.2
* Visual Studio Code version: 1.32.3

**Comment by caroline-church** [comment]
@Th1rstyGiant On the first point you can currently just click instantiate and this will let you instantiate an open project, a package, or an installed smart contract. 

On the point of bumping the version number we have had this request before and decided that if you are needing to iterate alot then you should be using dev mode and debugging the smart contract. That way you can keep making changes and you don't need to go round the loop lots. We are also currently making this easer by adding in functionality so that if you stop the debugger and start it again you can choose if it will package and install or just start the debugger (see issue #703)
