### ISSUE TITLE
When trying to create a new project without generator, error message isn't helpful.

### ISSUE THREAD

**Issue by EdProsser** [IBM-Blockchain/blockchain-vscode-extension#87]
After installing the VSCode extension, if you run the create project command, the command fails with the "Issue determining smart contract languages" error message.

**Comment by heatherlp** [comment]
This can be closed, based off various updates delivered recently. Currently the extension installs the generator if it isn't installed, and the user sees progress boxes for these tasks. If the extension fails to find the available contract languages, it's because they are missing from the package.json of the generator, and the error message will read: 'Issue determining available smart contract language options: Contract languages not found in package.json', which is more descriptive than the original message
